SENSOR_TETAP = [

"WDBOSHARTONO",
"WDBOSITASOFIANI",
"WDBOSWILLYHALIM",

"CRMHARTONO",
"CRMITASOFIANI",
"CRMWILLYHALIM",

"ANGKABETCRMHARTONO",
"ANGKABETCRMITASOFIANI",
"ANGKABETCRMWILLY",

"PULITOTOCRMHARTONO",
"PULITOTOCRMITASOFIANI",
"PULITOTOCRMWILLY",

"WDBOSCRMFEBRIYANDI",
"WDBOSCRMTEDDY",
"WDBOSCRMJULIANANDIKA",
"WDBOSCRMGILBERT",

"CRMDEVIN",
"CRMYEFTA",
"CRMHENDRA",
"CRMANDI",
"CRMYORDAN",

"LATOTOCRMFEBRIYANDI",
"LATOTOCRMTEDDY",
"LATOTOCRMGILBERT",

"DEPOBOSCRMFEBRIYANDI",
"DEPOBOSCRMTEDDY",
"DEPOBOSJULIANANDIKA",

"ANGKABETCRMGILBERT",
"ANGKABETCRMTEDDY",
"ANGKABETCRMJULIAN",
"ANGKABETFEBRIYANDI",

"PULITOTOCRMGILBERT",
"PULITOTOCRMTEDDY",
"PULITOTOCRMJULIAN",
"PULITOTOFEBRIYANDI"

]